Nuklon/Steam-Economy-Enhancer

- code.user.js
> Add inventory label disable option

- code.user.js
> Listings control buttons affect only filtered listings #114

- code.user.js
Fixes #108.
Also fixes not caching selected item which could possibly cause wrong info to be shown if you selected a different item fast enough.
> Fix multi selection creating infinite timers

- code.user.js
plagiarised from [2019 comment by @climbingstar](https://github.com/Nuklon/Steam-Economy-Enhancer/issues/94#issuecomment-539221164)
closes #94
> Include non-overpriced items for Relist Selected

- code.user.js
> Correctly remove buy orders

- code.user.js
seems like it was added for list.js, but it doesn't need it
> pagination.js is unused

- code.user.js
> Use Valve's v_currencyformat

- code.user.js
> Fix getting goo value

- code.user.js
> Add progress bar for market operations

- .editorconfig
- code.user.js
- eslint.config.mjs
Fixes #133.
Did a minor cleanup of the settings and market buttons.
> Use template literals

- code.user.js
> Bump code.user.js version

- code.user.js
> fix: missing `Select all from page` button

- code.user.js
> Do not run price labels code at all in tradeoffers if disabled

- code.user.js
Fixes items with question marks and stuff like that.
Valve does this:
```js
var elMarketLink = new Element( 'a', {
'href': 'https://steamcommunity.com/market/listings/' + item.appid + '/' + encodeURIComponent( strMarketName )
} );
elMarketLink.update( 'View in Community Market' );
```
> Escape view in market links

- code.user.js
Somehow missed this bit in #243.
> Fix tradeoffer price labels

- code.user.js
> fix: getActiveInventory() is null (#253)

- code.user.js
> feat: enable `Select all from page` button on counter offers

- code.user.js
> Fix: could not find a list matching elem

- code.user.js
Skip entry if it has missing assetInfo . (possibly a buy entry?) 
This appears to fix #257
> fix: Skip over listing when no asset info

- code.user.js
This pull request refactors the `request` function in `code.user.js` to enhance its reliability and manageability. Key changes include introducing a request queue system, adding error handling improvements, and implementing rate-limiting logic to avoid server overload.
* Replaced the previous implementation with a request queue system (`request.queue`) to ensure sequential execution of requests and prevent overlapping. Added a `request.pending` flag to track ongoing requests.
* Introduced a `request.stopped` flag to halt further requests in case of critical errors, improving robustness.
* Improved error handling by providing detailed error information, including HTTP status codes, textual descriptions, and response data, making debugging easier.
* Added dynamic delay adjustments based on …
> refactor: update request function

- code.user.js
Reverts Nuklon/Steam-Economy-Enhancer#273
> Revert "refactor: update request function"

- code.user.js
This PR allows to control spinners with less code blocks.
> refactor: replace spinner blocks with reusable functions
