- README.md
- code.user.js
This change makes the script work again in Greasemonkey, fixing the sandbox problem of issue #74 by using `unsafeWindow` to access the global variables.
It should also work in Tampermonkey and Violentmonkey (not tested) since they also support `unsafeWindow`.
> Fix for Greasemonkey

- code.user.js
Rationale: when you have a lot of lowest-value market listings (such as 0,03 euro), it makes little sense to check prices for them, as user is already selling them at the lowest possible value, and if the current value was higher then the item would've been sold out already. This is my own planned use case, and this is why I've set this option to 0,03. However, I've made the field flexible so users can decide on their own what prices exactly they want to skip, and if at all (default is to not use this feature).
I'm absolutely awful at javascript, so please forgive me for any screwups, and feel free to correct them. The code seems to work fine for me and I also didn't find any bugs.
Thanks.
> Implement optional price check skip

- code.user.js
This addresses issues #109 and #115 
When appropriate, depending on the error message, this will re-add a listing to the sell queue and then pause the queue for a few seconds.  In effect, this will pause the queue while 250 listings are awaiting confirmation.  It will also retry until success for certain error messages which tell the user to either wait or retry.
The errors received from Steam are represented only by localized strings, and so this change will only impact English speakers until other language strings are added to ``messageList``.  Retry until success will only happen when selling from the Inventory page.  No changes where made to what happens on error when selling from a Market Page.  However, now that an error is being reported, it should retry on the first error and …
> Retry listing on certain error messages

- code.user.js
Steam items have elements with the class `item_owner_actions visible` but other games inventories do not, and the market button is added to it.  
That element is hidden on almost all other games I've checked, causing the problem described in other Issues.  
Still not sure if a whole new button is the right way to have the "View in Community Market" link, but this fixes the missing problem.  
Also removed a break tag `<br/>`  on the added button because it causes unnecessary space between buttons on other items, and it is still normal for the steam ones.
Fixes #112
> Fixes #112 "View in Community Market" not showing on other games inventories.

- code.user.js
There is no unsafeWindow when injecting js
> remove unsafeWindow when using injectJs

- code.user.js
The helper creates buttons that will sell an item for 0,02 EUR/USD which is too low for creating a transaction. The reason why everything in the market costs $0,03 or more is because of the maths behind when splitting revenue into 3 parts. I am not sure how high the minimum is for other (especially low-value) currencies, but this should be a beginning.  
Great script btw!
> removed quicksell btn for too low (invalid) prices

- code.user.js
Repro:
1. Select some item
2. Use inventory filter/search so it gets hidden
3. The "Sell 10 items"/etc buttons should update to account only for visible selected items
This also fixes when selecting some items, filtering, and selecting other items still considers not visible items as selected.
> Recalculate selection based buttons after using filters

- code.user.js
I just wanted to turn all my duplicate items into gems. To be fair this is the first time for me doing stuff in JS, but `sellAllDuplicateItems()` was already providing a mechanism to filter out all duplicate items. So this part wasn't this hard. I tried to follow the general code style as well.
Preview of the new button:
Feel free to give me any input. Like I said JS is kinda new for me.
This relates to #170.
> Added functionality to turn all duplicates into gems

- README.md
- code.user.js
Displays the total number of items in a trade, rather than just the number of unique items, and replaces the old text with "Number of unique items" instead of "Number of items".
Added "Select 5/25/100" to the Community Market Page allowing people with tons of items to bulk select without clicking on each one or selecting all their listings.
> Total number of items on trade window, Select 5/25/100 on Community Market listing page.

- code.user.js
Currently, 'Sell item Manual' is broken when there are some characters, such as ampersand (e.g. Dreams & Nightmares Case), in the item name. Replacing `encodeURI` with `encodeURIComponent` should fix this.
> fix: use encodeURIComponent when building multisell URL

- code.user.js
Disabling this setting skips loading market info for each selected item.
I also moved code to move the market/booster buttons outside of the xhr request so that these buttons appear instantly.
> Add a setting to disable quick sell buttons

- .github/workflows/lint.yml
- .gitignore
- code.user.js
- eslint.config.mjs
- package.json
Only basic config for now, more rules can be enabled in the future. I also added a CI job to run this.
> Add eslint

- code.user.js
They switched to a websocket in 2018, so setting this bool only really prevents updating the HTML dom, it doesn't do any http requests.
https://github.com/SteamDatabase/SteamTracking/commit/f4c982e072bfa67676457af938986f195605374a?diff=split&w=0
> Remove g_bMarketWindowHidden hack

- code.user.js
Fixes the constant /my/inventory redirects when relisting items from market.
> Improve getting inventory url on market page

- code.user.js
> Prevent corrupted page sizes for market listings

- code.user.js
Makes them space well when they overflow.
> Use flexbox for the buttons

- code.user.js
- eslint.config.mjs
- package.json
- **Remove unused vars**
- **Fix up globals**
- **Change var to let/const**
- **Enable stylistic rules for consistent style**
Probably a pain to review (you can ignore whitespace changes at least).
> Cleanup with eslint rules

- code.user.js
Hopefully fixes #95, as their parser is aware of the currency symbols it should work fine in the context of currently displayed prices on the page.
> Use Valve's GetPriceValueAsInt when sorting by price

- code.user.js
Steam changed rate limits on various endpoints, including market
Would be cool to see adjustable delay between market actions
ref: https://github.com/Nuklon/Steam-Economy-Enhancer/issues/219
> Add adjustable delay between market actions

- code.user.js
Valve's code removes the listing via `$$('.listing_' + this.m_ulListingId)` which seems to work just fine with the paginated table, so I don't see a reason to reload the page here.
> Do not reload the page when removing a market listing

- code.user.js
It matches the code in `calculateSellPriceBeforeFees`
```
const shouldUseAverage = getSettingWithDefault(SETTING_PRICE_ALGORITHM) == 1;
else if (historyPrice < listingPrice || !shouldUseAverage) {
calculatedPrice = listingPrice;
}
```
`calculateAverageHistoryPriceBeforeFees` returns 0 if history is null.
> Do not fetch price history if price algorithm does not require it

- code.user.js
Trying to fix raw string issue for GetPriceValueAsInt
#222
> Fix issue #222

- code.user.js
Capability to list stacked items and math formulas to correctly display the price for such items.
"My Market Count" example
"Sell All" example
Unfortunately, I couldn't find a good solution to fix the ugliest line to find the amount of items.
```js
const amount = Number(unsafeWindow.g_rgAssets[appid][contextid][assetid].amount);
```
If we take a pure HTML string, it will cause problems with items that have a number at the beginning of the name.
> Items stack listing

- code.user.js
Ignore listing according to the final price.
Setup menu example
"Sell all" example
At the moment, this pull request has a conflict with my another pull request #233. So, depending on what is accepted and how, I will fix my code.
> Ignore listing by price

- code.user.js
Fixes #250. I am getting the 400 rejected response on `/market/sellitem`:
`{"success":false,"message":"Missing parameters in SellItem request"}`
For some reason, `amount` is not sent in the payload:
```
sessionid: ...
appid: 753
contextid: 6
assetid: 34121389221
price: 15
```
However, if I fix this line (503) `amount: item.amount` to `amount: item.amount || 1`, it obviously sends the `1` and returns with a `200` response:
```
{
"success": true,
...
}
``` 
Feel free to ask questions!
> Fix a bug with item.amount sometimes being undefined (#250)

- .github/ISSUE_TEMPLATE/bug.yml
A minor improvement, but I guess is fair to ask for the URL where the problem was found for faster support.
> chore: force users to share the affected URL on bugs.

- .github/ISSUE_TEMPLATE/bug.yml
> fix: syntax error at bug.yml (regression)

- code.user.js
In some places instead of `ERROR_FAILED` callbacks may return `ERROR_DATA`.
In that case error handling won't work as expected.
> fix: update error handling to check for ERROR_SUCCESS instead of ERROR_FAILED

- code.user.js
after merging https://github.com/Nuklon/Steam-Economy-Enhancer/pull/274, functions now actually waits before inventory would be loaded, rather then before
but nested inventories (CAppwideInventory) are not marks as fully loaded at `LoadUntilConditionMet` calls
so, script stucks indefinitely at inventories load at nested inventory (like 753_0)
this pr fixed that with a tiny trick
> fix: fixed nested inventories load

- code.user.js
This PR fixes market progress bar after https://github.com/Nuklon/Steam-Economy-Enhancer/pull/279
Buy-orders retrieves without pagination, so they can't update progress bar later like sell-orders do.
> fix: reset progress bar in market listings

- code.user.js
This PR fixes unhandled errors after clicking buttons when market lists are empty.
> fix: add null check for marketList in selection handling

- code.user.js
This PR adds a bit of tolerance for fatal errors.
Before this PR, request stops after first fatal error, now it's allows to get 5 errors until request will be stopped.
Reset-window chosen for 5 minutes, because other code blocks has delaying mechanism with 30-45s before retrying request. Plus some time for requests to the server. So, I guess 5 minutes is OK.
This can be useful, if:
- Steam performs background session refresh, while SEE sent request sent with old session data, in result - 401
(ref: https://community.fastly.steamstatic.com/public/shared/javascript/auth_refresh.js, session refreshes automatically, closer to jwt exp)
- User gets 429 error, which has reset-window in 1 minute (don't seen this in Steam, but it can be, and this is common everywhere)
Maybe additional delay …
> feat(request): add soft failure tolerance

- code.user.js
Based on https://github.com/Nuklon/Steam-Economy-Enhancer/pull/290
This PR adds spinner while inventories loads, if user clicked actions buttons.
If inventory is large enough and it's not loaded yet, user might think that script is not doing anything after clicking buttons.
About redundant 'removeSpinner' - this is needed, because we can't use 'promise.finally' here.
Another spinner might been rendered already. It's fine, because every time spinner calls, the previous one removes.
But in case of code consistency, better to remove spinner explicitly.
Code can be a bit shorter, for example, removing errors block at 'loadAllInventories', because we don't actually awaits errors.
'loadAllInventories' will never reject, right now and before recent changes.
But this is the thing to dealt with at …
> feat: add spinner in actions while inventory loads

- code.user.js
ref: https://github.com/Nuklon/Steam-Economy-Enhancer/issues/292
`loadAllInventories` actually will never reject errors. It will hang indefinitely if error occurs.
I guess, that's fine, because we don't know the real cause of the error and probably don't want to do anything at this point.
About user notifications, like
```js
logDOM('Could not retrieve the inventory...')
```
There is no need about that, because Steam itself will notify user about an error, if was one.
Additionally, fixed code style in some places.
> refactor(inventory): remove loadAllInventories errors handling

- code.user.js
This PR adds ability to skip prices load for removing items.
This will help:
- speed up removing
- making less requests to the server
- remove items while auto-relisting enabled
> feat: don't update removing listings

- code.user.js
Previous one arrow were not visible at macOS.
New ones is not bad and visible at Windows and macOS (other os wasn't tested).
> fix(ui): update sorting arrows in market listing tables
